# Generated by Django 4.2.3 on 2023-11-04 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('personal_order_id', models.IntegerField(blank=True, verbose_name='personal order')),
                ('full_order_id', models.CharField(blank=True, unique=True, verbose_name='full order_id')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('total_price', models.IntegerField(blank=True, default=0)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='orders.order_status', verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Orders_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='count')),
                ('price_for_one', models.IntegerField(blank=True, default=0)),
                ('full_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders', to_field='full_order_id', verbose_name='order id')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orders_item',
            constraint=models.CheckConstraint(check=models.Q(('count__gte', 0)), name='check_product_count'),
        ),
        migrations.AddConstraint(
            model_name='orders',
            constraint=models.CheckConstraint(check=models.Q(('personal_order_id__gte', 0)), name='check_personal_order_id'),
        ),
    ]
