# Generated by Django 4.2.3 on 2023-07-28 11:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_alter_productphoto_photo'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Full_orders',
            new_name='Orders_data',
        ),
        migrations.RenameModel(
            old_name='Orders_numbers',
            new_name='Orders_inform',
        ),
    ]
