# Generated by Django 4.2.3 on 2023-11-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='second_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
