# Generated by Django 4.2.3 on 2023-07-30 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_full_orders_orders_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_data',
            name='status',
            field=models.ForeignKey(default='collecting', on_delete=django.db.models.deletion.CASCADE, to='orders.order_status_types', verbose_name='status'),
        ),
    ]
