# Generated by Django 4.2.3 on 2023-08-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_data_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_data',
            name='total_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
