# Generated by Django 4.2.3 on 2023-08-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_data_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_inform',
            name='price_for_one',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
