# Generated by Django 4.2.3 on 2023-07-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(null=True),
        ),
    ]
