# Generated by Django 4.2.3 on 2023-07-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/photo_product/%Y/%m/%d', verbose_name='photo'),
        ),
    ]
