# Generated by Django 4.2.3 on 2023-07-31 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productphoto_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_create'], 'verbose_name': 'Products list'},
        ),
    ]
