# Generated by Django 4.2.3 on 2023-08-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_create'], 'verbose_name': 'Products list'},
        ),
    ]
